[package]
name = "telegram-worker"
version = "0.1.0"
edition = "2024"

[dependencies]
common = { version = "0.1.0", path = "../common" }
dotenvy = "0.15.7"
grammers-session = "0.10.0"
grammers-client = "0.10.0"
tokio = { version = "1.53.1", features = ["full"] }
tracing = "0.1.44"
chrono = "0.4.45"
sqlx = { version = "0.9.0", features = ["postgres", "tls-rustls", "macros", "migrate", "chrono", "runtime-tokio"] }
